/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export type CreateTaskDTOStatus = typeof CreateTaskDTOStatus[keyof typeof CreateTaskDTOStatus];


export const CreateTaskDTOStatus = {
  PENDING: 'PENDING',
  ON_HOLD: 'ON_HOLD',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
} as const;

export type CreateTaskDTOPriority = typeof CreateTaskDTOPriority[keyof typeof CreateTaskDTOPriority];


export const CreateTaskDTOPriority = {
  IMPORTANT: 'IMPORTANT',
  URGENT: 'URGENT',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  NORMAL: 'NORMAL',
} as const;

export interface CreateTaskDTO {
  /**
     * @minLength 3
     * @maxLength 100
     */
  title: string;
  /**
     * @minLength 3
     * @maxLength 500
     */
  description: string;
  status?: CreateTaskDTOStatus;
  priority?: CreateTaskDTOPriority;
  deadline?: string;
}

export type TaskDTOStatus = typeof TaskDTOStatus[keyof typeof TaskDTOStatus];


export const TaskDTOStatus = {
  PENDING: 'PENDING',
  ON_HOLD: 'ON_HOLD',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
} as const;

export type TaskDTOPriority = typeof TaskDTOPriority[keyof typeof TaskDTOPriority];


export const TaskDTOPriority = {
  IMPORTANT: 'IMPORTANT',
  URGENT: 'URGENT',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  NORMAL: 'NORMAL',
} as const;

export interface TaskDTO {
  id?: number;
  title?: string;
  description?: string;
  status?: TaskDTOStatus;
  priority?: TaskDTOPriority;
  deadline?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface ResponseDTOTaskDTO {
  message?: string;
  data?: TaskDTO;
  status?: boolean;
}

export interface ResponseDTOListTaskDTO {
  message?: string;
  data?: TaskDTO[];
  status?: boolean;
}

export type ResponseDTOVoidData = { [key: string]: unknown };

export interface ResponseDTOVoid {
  message?: string;
  data?: ResponseDTOVoidData;
  status?: boolean;
}

