/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  CreateTaskDTO,
  ResponseDTOListTaskDTO,
  ResponseDTOTaskDTO,
  ResponseDTOVoid
} from '../openAPIDefinition.schemas';


export type getTasksResponse200 = {
  data: ResponseDTOListTaskDTO
  status: 200
}

export type getTasksResponseSuccess = (getTasksResponse200) & {
  headers: Headers;
};
;

export type getTasksResponse = (getTasksResponseSuccess)

export const getGetTasksUrl = () => {




  return `/v1/tasks`
}

export const getTasks = async ( options?: RequestInit): Promise<getTasksResponse> => {

  const res = await fetch(getGetTasksUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTasksResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as getTasksResponse
}


export type createTaskResponse200 = {
  data: ResponseDTOTaskDTO
  status: 200
}

export type createTaskResponseSuccess = (createTaskResponse200) & {
  headers: Headers;
};
;

export type createTaskResponse = (createTaskResponseSuccess)

export const getCreateTaskUrl = () => {




  return `/v1/tasks`
}

export const createTask = async (createTaskDTO: CreateTaskDTO, options?: RequestInit): Promise<createTaskResponse> => {

  const res = await fetch(getCreateTaskUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTaskDTO)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createTaskResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as createTaskResponse
}


export type deleteTaskResponse200 = {
  data: ResponseDTOVoid
  status: 200
}

export type deleteTaskResponseSuccess = (deleteTaskResponse200) & {
  headers: Headers;
};
;

export type deleteTaskResponse = (deleteTaskResponseSuccess)

export const getDeleteTaskUrl = (id: number,) => {




  return `/v1/tasks/${id}`
}

export const deleteTask = async (id: number, options?: RequestInit): Promise<deleteTaskResponse> => {

  const res = await fetch(getDeleteTaskUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteTaskResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as deleteTaskResponse
}


export type updateTaskResponse200 = {
  data: ResponseDTOTaskDTO
  status: 200
}

export type updateTaskResponseSuccess = (updateTaskResponse200) & {
  headers: Headers;
};
;

export type updateTaskResponse = (updateTaskResponseSuccess)

export const getUpdateTaskUrl = (id: number,) => {




  return `/v1/tasks/${id}`
}

export const updateTask = async (id: number,
    createTaskDTO: CreateTaskDTO, options?: RequestInit): Promise<updateTaskResponse> => {

  const res = await fetch(getUpdateTaskUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTaskDTO)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateTaskResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as updateTaskResponse
}


export type updateTaskStatusResponse200 = {
  data: ResponseDTOTaskDTO
  status: 200
}

export type updateTaskStatusResponseSuccess = (updateTaskStatusResponse200) & {
  headers: Headers;
};
;

export type updateTaskStatusResponse = (updateTaskStatusResponseSuccess)

export const getUpdateTaskStatusUrl = (id: number,
    status: string,) => {




  return `/v1/tasks/${id}/status/${status}`
}

export const updateTaskStatus = async (id: number,
    status: string, options?: RequestInit): Promise<updateTaskStatusResponse> => {

  const res = await fetch(getUpdateTaskStatusUrl(id,status),
  {
    ...options,
    method: 'PATCH'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateTaskStatusResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as updateTaskStatusResponse
}


